[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-static",
    "-C", "link-arg=-static-libgcc", 
    "-C", "link-arg=-static-libstdc++",
    "-C", "link-arg=-Wl,--allow-multiple-definition",
    "-C", "link-arg=-Wl,--whole-archive",
    "-C", "link-arg=-Wl,--no-whole-archive",
    "-L", "/mingw64/lib",
    "-l", "static=gtk-4",
    "-l", "static=adwaita-1",
    "-l", "static=graphene-1.0",
    "-l", "static=gstreamer-1.0",
    "-l", "static=gstaudio-1.0",
    "-l", "static=gstplayer-1.0",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
]

[env]
# Force static linking for all components
PKG_CONFIG_ALL_STATIC = "1"
PKG_CONFIG_ALLOW_CROSS = "1"
GSTREAMER_1_0_STATIC = "1"
GTK4_STATIC = "1"
LIBADWAITA_STATIC = "1"
GRAPHENE_STATIC = "1"

# Library search paths
PKG_CONFIG_PATH = "/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig"
PKG_CONFIG_LIBDIR = "/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig"

# Linker flags
LDFLAGS = "-static -static-libgcc -static-libstdc++"
CFLAGS = "-static"
CXXFLAGS = "-static"