[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-C", "link-arg=-static",
    "-C", "link-arg=-static-libgcc", 
    "-C", "link-arg=-static-libstdc++",
    "-C", "target-feature=+crt-static",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
]

[env]
# Static linking for Windows
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_ALL_STATIC = "1"
GSTREAMER_1_0_STATIC = "1"
GTK4_STATIC = "1"